# Generated by Django 4.2.6 on 2023-10-24 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionLuces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_signal_late', models.DateTimeField()),
                ('ip', models.CharField(max_length=30, unique=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLuces.aulas')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLuces.tiposensores')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosLuces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLuces.sensores')),
            ],
        ),
        migrations.CreateModel(
            name='Interacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('encendido', 'encendido'), ('apagado', 'apagado')], max_length=10)),
                ('fecha', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLuces.sensores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionLuces.usuarios')),
            ],
        ),
    ]
