# Generated by Django 4.2.6 on 2023-10-31 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLuces', '0002_aulas_tiposensores_remove_usuarios_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='last_signal_late',
        ),
        migrations.AddField(
            model_name='aulas',
            name='ip',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aulas',
            name='last_signal_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 21, 10, 26, 831928)),
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='tipo',
            field=models.CharField(choices=[('encendido', 'encendido'), ('apagado', 'apagado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='tipo',
            field=models.CharField(choices=[('fotosensible', 'fotosensible'), ('rele', 'rele')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TipoSensores',
        ),
    ]
