# Generated by Django 4.2.4 on 2023-10-24 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionLuces', '0002_aulas_tiposensores_remove_usuarios_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
