# Generated by Django 4.2.6 on 2023-10-31 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLuces', '0004_alter_aulas_last_signal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='last_signal_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 20, 36, 54, 899910)),
        ),
    ]
