# Generated by Django 4.2.6 on 2023-11-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLuces', '0003_alter_interacciones_usuario_delete_usuarios'),
        ('GestionLuces', '0005_alter_aulas_last_signal_date'),
    ]

    operations = [

    ]
