# Generated by Django 4.2.4 on 2023-11-08 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLuces', '0006_merge_20231107_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='last_signal_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 20, 49, 37, 920259)),
        ),
    ]
