# Generated by Django 4.2.4 on 2023-11-09 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLuces', '0007_alter_aulas_last_signal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensores',
            old_name='aula',
            new_name='aula_id',
        ),
        migrations.AlterField(
            model_name='aulas',
            name='last_signal_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 21, 36, 11, 886883)),
        ),
    ]
