# Generated by Django 4.2.4 on 2023-11-09 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLuces', '0008_rename_aula_sensores_aula_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensores',
            old_name='aula_id',
            new_name='aula',
        ),
        migrations.AlterField(
            model_name='aulas',
            name='last_signal_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 21, 40, 33, 374502)),
        ),
    ]
